### ISSUE TITLE
how to establish tls connect without private key

### ISSUE THREAD

**Issue by qin11152** [rgerganov/shanocast#1]
Hi bro, I'm interested in googlecast receiver. I read your article(https://xakcop.com/post/shanocast/) and realized that you got the certificate and the corresponding precomputed signatures.
But  you didn't get the private key. Now, I wonder how you establish the tls connect only with certificate without private key.

**Comment by rgerganov** [comment]
I dumped the private key with `jnitrace` as I explained in the blog post.

**Comment by qin11152** [comment]
can you share the private key，I can pay for it.
